//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoSatGCS.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoSatGCS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sAdd {
            get {
                return ResourceManager.GetString("sAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sAdvanced {
            get {
                return ResourceManager.GetString("sAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sApply {
            get {
                return ResourceManager.GetString("sApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sArchive {
            get {
                return ResourceManager.GetString("sArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attach과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sAttach {
            get {
                return ResourceManager.GetString("sAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sBackward {
            get {
                return ResourceManager.GetString("sBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Board Revision과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sBoardRevision {
            get {
                return ResourceManager.GetString("sBoardRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCancel {
            get {
                return ResourceManager.GetString("sCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCheckAll {
            get {
                return ResourceManager.GetString("sCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sClear {
            get {
                return ResourceManager.GetString("sClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sClose {
            get {
                return ResourceManager.GetString("sClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCommand {
            get {
                return ResourceManager.GetString("sCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCommandFile {
            get {
                return ResourceManager.GetString("sCommandFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCommandSet {
            get {
                return ResourceManager.GetString("sCommandSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCommit {
            get {
                return ResourceManager.GetString("sCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sConfiguration {
            get {
                return ResourceManager.GetString("sConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sConnect {
            get {
                return ResourceManager.GetString("sConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CPU Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCPUType {
            get {
                return ResourceManager.GetString("sCPUType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDashboard {
            get {
                return ResourceManager.GetString("sDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDatabase {
            get {
                return ResourceManager.GetString("sDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Debug과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDebug {
            get {
                return ResourceManager.GetString("sDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDelete {
            get {
                return ResourceManager.GetString("sDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDeleteAll {
            get {
                return ResourceManager.GetString("sDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDescription {
            get {
                return ResourceManager.GetString("sDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deselect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDeselect {
            get {
                return ResourceManager.GetString("sDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detach과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDetach {
            get {
                return ResourceManager.GetString("sDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDisplay {
            get {
                return ResourceManager.GetString("sDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downlink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDownlink {
            get {
                return ResourceManager.GetString("sDownlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDownload {
            get {
                return ResourceManager.GetString("sDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sEdit {
            get {
                return ResourceManager.GetString("sEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sEnable {
            get {
                return ResourceManager.GetString("sEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sEncryption {
            get {
                return ResourceManager.GetString("sEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sError {
            get {
                return ResourceManager.GetString("sError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sExecute {
            get {
                return ResourceManager.GetString("sExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sExecuteAll {
            get {
                return ResourceManager.GetString("sExecuteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute Once과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sExecuteOnce {
            get {
                return ResourceManager.GetString("sExecuteOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sExport {
            get {
                return ResourceManager.GetString("sExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFile {
            get {
                return ResourceManager.GetString("sFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Share과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFileShare {
            get {
                return ResourceManager.GetString("sFileShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flags과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFlags {
            get {
                return ResourceManager.GetString("sFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sForward {
            get {
                return ResourceManager.GetString("sForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Functions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFunctions {
            get {
                return ResourceManager.GetString("sFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFWConfig {
            get {
                return ResourceManager.GetString("sFWConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FW Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFwType {
            get {
                return ResourceManager.GetString("sFwType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FW Version Major과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFwVersionMajor {
            get {
                return ResourceManager.GetString("sFwVersionMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FW Version Minor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sFwVersionMinor {
            get {
                return ResourceManager.GetString("sFwVersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sGeneral {
            get {
                return ResourceManager.GetString("sGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sGeneralConfig {
            get {
                return ResourceManager.GetString("sGeneralConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ground Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sGroundTrack {
            get {
                return ResourceManager.GetString("sGroundTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sGroup {
            get {
                return ResourceManager.GetString("sGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sHide {
            get {
                return ResourceManager.GetString("sHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sImport {
            get {
                return ResourceManager.GetString("sImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sInvalid {
            get {
                return ResourceManager.GetString("sInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ModuleConfig과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sModuleConfig {
            get {
                return ResourceManager.GetString("sModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module Mac과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sModuleMac {
            get {
                return ResourceManager.GetString("sModuleMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ModuleType과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sModuleType {
            get {
                return ResourceManager.GetString("sModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sName {
            get {
                return ResourceManager.GetString("sName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sOk {
            get {
                return ResourceManager.GetString("sOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sOkSelect {
            get {
                return ResourceManager.GetString("sOkSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orbital Elements과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sOrbitalElements {
            get {
                return ResourceManager.GetString("sOrbitalElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sOut {
            get {
                return ResourceManager.GetString("sOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sParameters {
            get {
                return ResourceManager.GetString("sParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPassCommand {
            get {
                return ResourceManager.GetString("sPassCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Queue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPassQueue {
            get {
                return ResourceManager.GetString("sPassQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPassSchedule {
            get {
                return ResourceManager.GetString("sPassSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pass Time Line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPassTimeLine {
            get {
                return ResourceManager.GetString("sPassTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPreview {
            get {
                return ResourceManager.GetString("sPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sProcessor {
            get {
                return ResourceManager.GetString("sProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sProperties {
            get {
                return ResourceManager.GetString("sProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pull과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPull {
            get {
                return ResourceManager.GetString("sPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Push과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sPush {
            get {
                return ResourceManager.GetString("sPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRadio {
            get {
                return ResourceManager.GetString("sRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRefresh {
            get {
                return ResourceManager.GetString("sRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRemove {
            get {
                return ResourceManager.GetString("sRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRename {
            get {
                return ResourceManager.GetString("sRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRestart {
            get {
                return ResourceManager.GetString("sRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Results과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sResults {
            get {
                return ResourceManager.GetString("sResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RoSatProcessor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRoSatProcessor {
            get {
                return ResourceManager.GetString("sRoSatProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRun {
            get {
                return ResourceManager.GetString("sRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRunAll {
            get {
                return ResourceManager.GetString("sRunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satellite Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSatelliteInfo {
            get {
                return ResourceManager.GetString("sSatelliteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Satellite ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSatID {
            get {
                return ResourceManager.GetString("sSatID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSave {
            get {
                return ResourceManager.GetString("sSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sScheduler {
            get {
                return ResourceManager.GetString("sScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSearch {
            get {
                return ResourceManager.GetString("sSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSelect {
            get {
                return ResourceManager.GetString("sSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSerial {
            get {
                return ResourceManager.GetString("sSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSetting {
            get {
                return ResourceManager.GetString("sSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sShared {
            get {
                return ResourceManager.GetString("sShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sShow {
            get {
                return ResourceManager.GetString("sShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSize {
            get {
                return ResourceManager.GetString("sSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sStart {
            get {
                return ResourceManager.GetString("sStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sStop {
            get {
                return ResourceManager.GetString("sStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub Module과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSubModule {
            get {
                return ResourceManager.GetString("sSubModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TLE List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sTLEList {
            get {
                return ResourceManager.GetString("sTLEList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sType {
            get {
                return ResourceManager.GetString("sType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type Dictionary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sTypeDictionary {
            get {
                return ResourceManager.GetString("sTypeDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncheck All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUncheckAll {
            get {
                return ResourceManager.GetString("sUncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsaved Changes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUnsavedChanges {
            get {
                return ResourceManager.GetString("sUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUpdate {
            get {
                return ResourceManager.GetString("sUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uplink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUplink {
            get {
                return ResourceManager.GetString("sUplink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUpload {
            get {
                return ResourceManager.GetString("sUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sWarning {
            get {
                return ResourceManager.GetString("sWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat. Preset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarPreset {
            get {
                return ResourceManager.GetString("TopBarPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarSchedule {
            get {
                return ResourceManager.GetString("TopBarSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarSerialPort {
            get {
                return ResourceManager.GetString("TopBarSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarStatus {
            get {
                return ResourceManager.GetString("TopBarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarTime {
            get {
                return ResourceManager.GetString("TopBarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zAreYouSure {
            get {
                return ResourceManager.GetString("zAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close anyway?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zCloseAnyway {
            get {
                return ResourceManager.GetString("zCloseAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command already exists in the list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zCommandAlreadyExists {
            get {
                return ResourceManager.GetString("zCommandAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to execute anyway?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zExecuteAnyway {
            get {
                return ResourceManager.GetString("zExecuteAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execution timeout.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zExecutionTimeout {
            get {
                return ResourceManager.GetString("zExecutionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension must be json.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zExtensionJson {
            get {
                return ResourceManager.GetString("zExtensionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extension mismatch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zExtensionMismatch {
            get {
                return ResourceManager.GetString("zExtensionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to execute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zFailToExecute {
            get {
                return ResourceManager.GetString("zFailToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail to load과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zFailToLoad {
            get {
                return ResourceManager.GetString("zFailToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zFileNotFound {
            get {
                return ResourceManager.GetString("zFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid size.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zInvalidSize {
            get {
                return ResourceManager.GetString("zInvalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No such file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zNoSuchFile {
            get {
                return ResourceManager.GetString("zNoSuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null Argument과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zNullArgument {
            get {
                return ResourceManager.GetString("zNullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid parameter exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zParametersInvalid {
            get {
                return ResourceManager.GetString("zParametersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parse Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zParseError {
            get {
                return ResourceManager.GetString("zParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to replace it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zReplaceIt {
            get {
                return ResourceManager.GetString("zReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same command exists과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zSameCommandExists {
            get {
                return ResourceManager.GetString("zSameCommandExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same file exists과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zSameFileExists {
            get {
                return ResourceManager.GetString("zSameFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save anyway?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zSaveAnyway {
            get {
                return ResourceManager.GetString("zSaveAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serialize Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zSerializeError {
            get {
                return ResourceManager.GetString("zSerializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Struct Enum Parse Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zStructEnumParseError {
            get {
                return ResourceManager.GetString("zStructEnumParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type not found과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string zTypeNotFound {
            get {
                return ResourceManager.GetString("zTypeNotFound", resourceCulture);
            }
        }
    }
}
