//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoSatGCS.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoSatGCS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Window과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuWindow {
            get {
                return ResourceManager.GetString("MenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sApply {
            get {
                return ResourceManager.GetString("sApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Archive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sArchive {
            get {
                return ResourceManager.GetString("sArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sCommand {
            get {
                return ResourceManager.GetString("sCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sConnect {
            get {
                return ResourceManager.GetString("sConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dashboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDashboard {
            get {
                return ResourceManager.GetString("sDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDatabase {
            get {
                return ResourceManager.GetString("sDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downlink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sDownlink {
            get {
                return ResourceManager.GetString("sDownlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ground Track과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sGroundTrack {
            get {
                return ResourceManager.GetString("sGroundTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sProcessor {
            get {
                return ResourceManager.GetString("sProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sRefresh {
            get {
                return ResourceManager.GetString("sRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scheduler과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sScheduler {
            get {
                return ResourceManager.GetString("sScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSerial {
            get {
                return ResourceManager.GetString("sSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sSetting {
            get {
                return ResourceManager.GetString("sSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uplink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sUplink {
            get {
                return ResourceManager.GetString("sUplink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat. Preset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarPreset {
            get {
                return ResourceManager.GetString("TopBarPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Schedule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarSchedule {
            get {
                return ResourceManager.GetString("TopBarSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarSerialPort {
            get {
                return ResourceManager.GetString("TopBarSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarStatus {
            get {
                return ResourceManager.GetString("TopBarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Local Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TopBarTime {
            get {
                return ResourceManager.GetString("TopBarTime", resourceCulture);
            }
        }
    }
}
